project_id = "yqsqjdivrylevaczeejd"

[functions.send-purchase-email]
verify_jwt = false

[functions.handle-payment-webhook]
verify_jwt = false

[functions.send-scheduled-emails]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = true

[functions.admin-resend-welcome-email]
verify_jwt = true

[functions.cleanup-analytics]
verify_jwt = false
